### PR TITLE
exclude qtum exec

### PR DESCRIPTION
**Pull request by henryzbw**
Exclude all the qtum exec

### CODE REVIEW

**Comment by dwalintukan** [comment]
Can you exclude all the binaries? /bin

**Comment by frankobe** [comment]
@dwalintukan I ask henry to keep the structure while removing all binary

**Comment by dwalintukan** [comment]
👍

**Comment by dwalintukan** [comment]
Oops sorry I already fixed this in #97 . Removed the cached binaries from the repo remotely,.

**Comment by henryzbw** [comment]
@dwalintukan frank taught me this way is easy to do. @frankobe do i need to move them all into the .gitignore in the root?

**Comment by dwalintukan** [comment]
@henrybzw hm I see. Ok if @frankobe approves.

**Comment by henryzbw** [comment]
@frankobe Binary is removed.

**Comment by henryzbw** [comment]
can this be merged? it's been 4 days

**Comment by frankobe** [comment]
@henryzbw whats the structure now after Deric's pr? `master` has been updated so can u double check the behavior now?

**Comment by henryzbw** [comment]
@frankobe i just cloned one to local, bin folder does not exist, and qtum folder is still there with everything inside.

**Comment by dwalintukan** [comment]
you will have to rebuild it if you want the binary folder structure there. I removed the cached binaries in my last PR.

**Pull request merged**
