### PR TITLE
Remove throw from updateDB func

### PR DESCRIPTION
**Pull request by dwalintukan**

### CODE REVIEW

**Comment by dwalintukan** [comment]
@frankobe its not caught in the upper level here. `update_tx.js L33` is what it eventually comes up to, and didnt think it was a good idea to stop the rest of the promises in the array.

this issue it stemmed from encrypted wallets. if the user quits the app before the follow-up tx is executed in the current session, and then next time they launch the wallet will be locked and the follow-up tx will fail and cause the backend to hang due to an `Unhandled Promise Exception`.

**Comment by frankobe** [comment]
@dwalintukan i c. so the correct handle should catch it and ask user to unlock the wallet? If an error is thrown here, lots of sequential operation cant be completed.

**Comment by dwalintukan** [comment]
@frankobe if you have a suggestion for graph to send a message to UI for triggering the unlock wallet functionality, then we can make that happen.

that's why i took out the throw at the last point, so the rest of the operation wouldn't be blocked or skipped.

**Comment by frankobe** [comment]
@dwalintukan I saw serveral problems here and they can be addressed separately

1. Backend Hang -> Even though removing this throw will unfreeze backend, as wallet is locked, followup transasction will throw error too. As we dunt hv retry logic for transaction(probably wont), transaction table remains in a partial incorrect state and cant be corrected later. That's why I explicity throw an error here to pause/alert this error. We can save the init state on tx entities, and reset them when encoutering any errors. 

2. Pop user to unlock the wallet -> With wallet locked, sync events will work but all `send()` calls to qtumd will fail. An easy fix can be requesting user to unlock wallet before `startSync()`.

Let me know if this make sense to u

**Comment by dwalintukan** [comment]
@frankobe 
1. its true that the follow-up tx will fail, but the follow-up `Transaction obj` will not be inserted into the db. the error thrown from this tx will bubble up to `L110` and stop there. so the DB will just have the successful `Approve tx`, but the follow-up tx obj will not be inserted. granted, this is still an issue as users might wonder why an `Approve` went through and nothing else.

2. the wallet unlock dialog is part of the UI, not graphql. so in order to be able to have the user unlock it from graphql-side, we need to have some sort of IPC mechanism for BE and FE to talk to each other. AFAIK, electron doesn't have a form type of dialog, so we would have to have a separate static webpage for the Wallet Unlock in graph-side, which I would prefer not to do.

**Comment by dwalintukan** [comment]
closing as this issue is fixed in #238

**Pull request closed without merging**
