### PR TITLE
Sync threshold

### PR DESCRIPTION
**Pull request by dwalintukan**

### CODE REVIEW

**Comment by dwalintukan** [comment]
@frankobe sorry, still making a fix right now. something is up with the balance parsing.

**Comment by dwalintukan** [comment]
@frankobe this one is good to go now.

**Comment by frankobe** [comment]
@dwalintukan can u try remove `frankhu-optimizely` from reviewer, I approve it using wrong account by mistake

**Comment by frankobe** [comment]
@dwalintukan LGTM and Ship it

**Comment by dwalintukan** [comment]
@frankobe tried to remove your other acct but couldnt

**Pull request merged**
